import { readdir, readFile } from "node:fs/promises";
import * as path from "node:path";
import { remark } from "remark";
import { describe, expect, it } from "vitest";

import {
    generateAllPresetOutputs,
    getPresetExampleFileName,
    presetExamplesDirectory,
    presetsDirectory,
    renderPresetExampleDocument,
    renderPresetExamplesIndex,
} from "../scripts/preset-example-fixture.mjs";
import {
    type GitCliffPresetFileName,
    gitCliffPresetFileNames,
} from "../src/gitcliff-config.js";

type PresetOutputs = ReadonlyMap<string, string>;

const presetOutputsPromise = generateAllPresetOutputs();

const getPresetOutput = (
    outputs: PresetOutputs,
    fileName: GitCliffPresetFileName
): string => {
    const changelog = outputs.get(fileName);

    if (changelog === undefined) {
        throw new Error(`Missing rendered preset: ${fileName}`);
    }

    return changelog;
};

const expectValidGeneratedMarkdown = (changelog: string): void => {
    const lines = changelog.trim().split("\n");

    expect(remark().parse(changelog).type).toBe("root");
    expect(changelog).not.toMatch(/(?:\{%|%\}|\{\{|\}\}|\{#|#\})/v);
    expect(changelog).not.toMatch(/\b(?:NaN|null|undefined)\b/v);
    expect(changelog).not.toMatch(/^###\s*$/mv);
    expect(changelog).not.toMatch(/<!--\s*\d+\s*-->/v);
    expect(changelog).not.toContain("prepare for v1.1.0");
    expect(
        lines.some(
            (line, index) =>
                line.trim() === "" && lines[index + 1]?.trim() === ""
        )
    ).toBe(false);
};

const expectHeadingsInOrder = (
    changelog: string,
    headings: readonly string[]
): void => {
    const indexes = headings.map((heading) => changelog.indexOf(heading));

    expect(indexes.every((index) => index >= 0)).toBe(true);
    expect(
        indexes.every(
            (index, position) =>
                position === 0 || (indexes[position - 1] ?? Infinity) < index
        )
    ).toBe(true);
};

const expectProviderPresets = (outputs: PresetOutputs): void => {
    const azure = getPresetOutput(outputs, "azure-devops-keepachangelog.toml");

    expect(azure).toContain("## [1.1.0] - 2025-01-19");
    expect(azure).toContain(
        "https://dev.azure.com/acme/platform/_git/widget/branchCompare"
    );
    expect(azure).not.toContain("GBmaster");
    expect(azure).not.toContain("github.com/");

    const githubKeep = getPresetOutput(outputs, "github-keepachangelog.toml");

    expect(githubKeep).toContain("The format is based on [Keep a Changelog]");
    expect(githubKeep).toContain(
        "github.com/Nick2bad4u/example-package/compare/v1.0.0...v1.1.0"
    );

    const github = getPresetOutput(outputs, "github.toml");

    expect(github).toContain("## What's Changed in 1.1.0");
    expect(github).not.toContain("### ✨ Features");
    expect(github).toContain("*(backend)* add renderer #42");

    const gitlab = getPresetOutput(outputs, "gitlab-keepachangelog.toml");

    expect(gitlab).toContain(
        "https://gitlab.example/acme/widget/-/compare/v1.0.0...v1.1.0"
    );
    expect(gitlab).not.toContain("github.com/");
};

const expectCoreStylePresets = (outputs: PresetOutputs): void => {
    const cocogitto = getPresetOutput(outputs, "cocogitto.toml");

    expect(cocogitto).toContain("---");
    expect(cocogitto).toContain("**(backend)**");
    expect(cocogitto.indexOf("**(backend)**")).toBeLessThan(
        cocogitto.indexOf("**(cli)**")
    );
    expect(cocogitto.indexOf("**(cli)**")).toBeLessThan(
        cocogitto.indexOf("**(web)**")
    );
    expect(cocogitto).not.toContain("cocogitto/cocogitto");

    const detailed = getPresetOutput(outputs, "detailed.toml");

    expect(detailed).toContain("**Range:**");
    expect(detailed).toContain("Adds the renderer used by API consumers.");
    expect(detailed).toMatch(/Preset Example — \d+ files?, \+\d+, -\d+/v);

    const keepAChangelog = getPresetOutput(outputs, "keepachangelog.toml");

    expect(keepAChangelog).toContain("## [1.1.0] - 2025-01-19");
    expect(keepAChangelog).toContain(
        "github.com/Nick2bad4u/example-package/compare/v1.0.0...v1.1.0"
    );

    const minimal = getPresetOutput(outputs, "minimal.toml");

    expect(minimal).toContain("## 1.1.0 - 2025-01-19");
    expect(minimal).not.toContain("# Changelog");
    expect(minimal).not.toContain("generated by git-cliff");
    expect(minimal).toContain("*(web)* Add browser adapter");

    expectHeadingsInOrder(minimal, [
        "### ✨ Features",
        "### 🛠️ Bug Fixes",
        "### 🚜 Refactor",
        "### 📝 Documentation",
        "### ⚡ Performance",
        "### 🎨 Styling",
        "### 🧪 Testing",
        "### 🧹 Chores",
        "### 👷 CI/CD",
        "### 🔧 Build System",
        "### ⏪ Reverts",
        "### 📦 Dependencies",
        "### 🛡️ Security",
        "### 🛠️ Other Changes",
    ]);
};

const expectScopeAndStatisticsPresets = (outputs: PresetOutputs): void => {
    const scoped = getPresetOutput(outputs, "scoped.toml");

    expect(scoped).toContain("#### Backend");
    expect(scoped).toContain("#### Unscoped");
    expect(scoped).not.toContain("(backend) add renderer");

    const scopeSorted = getPresetOutput(outputs, "scopesorted.toml");

    expect(scopeSorted.indexOf("*(backend)*")).toBeLessThan(
        scopeSorted.indexOf("*(cli)*")
    );
    expect(scopeSorted).toContain("*(Unscoped)*");
    expect(scopeSorted).toContain("**BREAKING:** the legacy flag was removed.");

    const statistics = getPresetOutput(outputs, "statistics.toml");

    expect(statistics).toContain("### Release Statistics");
    expect(statistics).toContain("17 commits included.");
    expect(statistics).toContain("2 commits followed Conventional Commits.");
    expect(statistics).toContain("[#42]");
    expect(statistics).toContain("referenced 2 times.");

    const unconventional = getPresetOutput(outputs, "unconventional.toml");

    expect(unconventional).toContain("feat(cli)!: remove legacy flag #42");
    expect(unconventional).toContain(
        ":sparkles: [feat] (web) add browser adapter"
    );
    expect(unconventional).toContain("Improve assorted repository behavior");
};

const expectUserFacingPresets = (outputs: PresetOutputs): void => {
    for (const fileName of [
        "detailed-user-facing.toml",
        "minimal-user-facing.toml",
    ] as const) {
        const userFacing = getPresetOutput(outputs, fileName);

        expect(userFacing).toContain("### ✨ Features");
        expect(userFacing).toContain("### 🛠️ Bug Fixes");
        expect(userFacing).toContain("### ⚡ Performance");
        expect(userFacing).toContain("### ⏪ Reverts");
        expect(userFacing).toContain("### 🛡️ Security");
        expect(userFacing).not.toContain("### 🚜 Refactor");
        expect(userFacing).not.toContain("### 📝 Documentation");
        expect(userFacing).not.toContain("### 🎨 Styling");
        expect(userFacing).not.toContain("### 🧪 Testing");
        expect(userFacing).not.toContain("### 🧹 Chores");
        expect(userFacing).not.toContain("### 👷 CI/CD");
        expect(userFacing).not.toContain("### 🔧 Build System");
        expect(userFacing).not.toContain("### 📦 Dependencies");
        expect(userFacing).not.toContain("### 🛠️ Other Changes");
    }
};

const expectCustomPresets = (outputs: PresetOutputs): void => {
    const monorepo = getPresetOutput(outputs, "monorepo.toml");

    expect(monorepo).toContain("### Backend");
    expect(monorepo).toContain("#### ✨ Features");
    expect(monorepo).toContain("### Unscoped");

    const dependencyAudit = getPresetOutput(outputs, "dependency-audit.toml");

    expect(dependencyAudit).toContain("### 📦 Dependencies");
    expect(dependencyAudit).toContain("### 🛡️ Security");
    expect(dependencyAudit).toContain("[dependency] Update lodash");
    expect(dependencyAudit).not.toContain("### ✨ Features");

    const ledger = getPresetOutput(outputs, "change-ledger.toml");

    expect(ledger).toContain(
        "| Date | Category | Scope | Change | Commit | Author | Diff |"
    );
    expect(ledger).toContain("| ✨ Features | backend | add renderer #42 |");
    expect(ledger).toContain("github.com/Nick2bad4u/example-package/commit/");
};

describe("published git-cliff presets", () => {
    it("keeps every standalone config generated from the canonical parser contract", async () => {
        expect.hasAssertions();

        const files = (await readdir(presetsDirectory))
            .filter((fileName) => fileName.endsWith(".toml"))
            .toSorted((left, right) => left.localeCompare(right, "en"));
        const configs = new Map<string, string>(
            await Promise.all(
                files.map(
                    async (fileName): Promise<readonly [string, string]> => [
                        fileName,
                        await readFile(
                            path.join(presetsDirectory, fileName),
                            "utf8"
                        ),
                    ]
                )
            )
        );
        const scopeCapture = [
            'scope = "',
            "$",
            '{1}"',
        ].join("");
        const unconventionalConfig = configs.get("unconventional.toml");

        expect(files).toStrictEqual(
            gitCliffPresetFileNames.toSorted((left, right) =>
                left.localeCompare(right, "en")
            )
        );
        expect(files).toHaveLength(17);
        expect(files).not.toContain("cliff.toml");
        expect(
            configs
                .values()
                .every((config) =>
                    config.startsWith(
                        "# This file is generated by npm run presets:generate."
                    )
                )
        ).toBe(true);
        expect(
            configs.values().every((config) => config.includes(scopeCapture))
        ).toBe(true);
        expect(
            configs
                .values()
                .every(
                    (config) =>
                        config.includes("Bump (") &&
                        config.includes("from.*?to")
                )
        ).toBe(true);
        expect(unconventionalConfig).toMatch(/conventional_commits\s+= false/v);
        expect(
            configs
                .entries()
                .filter(([fileName]) => fileName !== "unconventional.toml")
                .every(([, config]) =>
                    /conventional_commits\s+= true/v.test(config)
                )
        ).toBe(true);
        expect(getPresetExampleFileName("github.toml")).toBe("github.md");
        expect(() => getPresetExampleFileName("github.md")).toThrow(
            "Expected a .toml preset filename"
        );
    });

    it("renders every style with its defining layout and parsing behavior", async () => {
        expect.hasAssertions();

        const presetOutputs = await presetOutputsPromise;

        expect(presetOutputs.size).toBe(17);

        for (const changelog of presetOutputs.values()) {
            expectValidGeneratedMarkdown(changelog);
        }

        expectProviderPresets(presetOutputs);
        expectCoreStylePresets(presetOutputs);
        expectScopeAndStatisticsPresets(presetOutputs);
        expectUserFacingPresets(presetOutputs);
        expectCustomPresets(presetOutputs);
    });

    it("keeps every committed documentation example synchronized", async () => {
        expect.hasAssertions();

        const presetOutputs = await presetOutputsPromise;
        const presetFileNames = presetOutputs.keys().toArray();
        const expectedExampleFileNames = ["README.md"];

        for (const presetFileName of presetFileNames) {
            expectedExampleFileNames.push(
                getPresetExampleFileName(presetFileName)
            );
        }

        const sortedExpectedExampleFileNames =
            expectedExampleFileNames.toSorted((left, right) =>
                left.localeCompare(right, "en")
            );
        const actualExampleFileNames = (await readdir(presetExamplesDirectory))
            .filter((fileName) => fileName.endsWith(".md"))
            .toSorted((left, right) => left.localeCompare(right, "en"));

        expect(actualExampleFileNames).toStrictEqual(
            sortedExpectedExampleFileNames
        );

        const index = await readFile(
            path.join(presetExamplesDirectory, "README.md"),
            "utf8"
        );

        expect(index.replaceAll("\r\n", "\n")).toBe(
            renderPresetExamplesIndex(presetFileNames)
        );
        expect(remark().parse(index).type).toBe("root");

        for (const [presetFileName, changelog] of presetOutputs) {
            const exampleFileName = getPresetExampleFileName(presetFileName);
            const example = await readFile(
                path.join(presetExamplesDirectory, exampleFileName),
                "utf8"
            );
            const normalizedExample = example.replaceAll("\r\n", "\n");

            expect(normalizedExample).toBe(
                renderPresetExampleDocument(presetFileName, changelog)
            );

            expectValidGeneratedMarkdown(normalizedExample);
        }
    });
});
